services:
  db:
    image: mysql:8.0
    container_name: taft_eats_db
    restart: always
    env_file: .env
    ports: 
      - "3307:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - ./mysql_data:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
